[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API helpers
[[redirects]]
  from = "/api/affirm-authorize"
  to = "/.netlify/functions/affirm-authorize"
  status = 200

[[redirects]]
  from = "/api/create-stripe-checkout"
  to = "/.netlify/functions/create-stripe-checkout"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200